### ISSUE TITLE
Clean Method

### ISSUE THREAD

**Issue by sco-tt** [stephanecoinon/mailtrap#3]
I've added a method on the Inbox class that implements the clean method:

https://mailtrap.docs.apiary.io/#reference/inbox/apiv1inboxesinboxidclean

Any objects to a PR?

**Comment by stephanecoinon** [comment]
@sco-tt  None at all, please go ahead :)

**Comment by sco-tt** [comment]
Submitted the PR. I used it for a pretty basic use case (unit testing), so it's pretty basic.

**Comment by stephanecoinon** [comment]
Done in #4 , thank you @sco-tt
